import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";

const interFont = Inter({
    adjustFontFallback: true,
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${interFont.className} h-full antialiased`}>
            <body>
                <main className="h-screen">
                    <AuthProvider>{children}</AuthProvider>
                </main>
            </body>
        </html>
    );
}
