import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";

const interFont = Inter({
    adjustFontFallback: true,
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${interFont.className} min-h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <main className="min-h-screen flex flex-col flex-1">
                    <AuthProvider>{children}</AuthProvider>
                    <Toaster position="top-right" />
                </main>
            </body>
        </html>
    );
}
